services:
  - type: web
    name: sentiment-analysis-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    autoDeploy: true
    branch: main
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
